LIBRARY PMCTLSPP INITINSTANCE TERMINSTANCE

PROTMODE

DESCRIPTION   '@#NB:X.XX.XX#@ public PM control class (c) nb-software 2001...2007'

DATA MULTIPLE NONSHARED READWRITE LOADONCALL

CODE LOADONCALL

SEGMENTS
   GLOBAL_SEG CLASS 'DATA' SHARED

EXPORTS
   _PM_Init         @1
