
;  This file was generated by the SOM Compiler.
;  FileName: D:\WORK\IBMC\AMOUSE\WPSDLL\AMouse.def.
;  Generated using:
;      SOM Precompiler somipc: 2.29.1.7
;      SOM Emitter emitdef: 2.42
LIBRARY AMouse INITINSTANCE
DESCRIPTION   '@#NB:X.XX.XX#@ WPS Class for Scroll Mouse (c) nb-software 2001...2007'
PROTMODE
DATA MULTIPLE NONSHARED LOADONCALL
EXPORTS
   AMouseCClassData
   AMouseClassData
   AMouseNewClass
   M_AMouseCClassData
   M_AMouseClassData
   M_AMouseNewClass
