# The actions included in this makefile are:
#   BIND::Resource Bind
#   COMPILE::CLC C
#   COMPILE::Resource Compile
#   COMPILE::SOM
#   LINK::CLC Link

.SUFFIXES:

.SUFFIXES: .c .idl .rc .res

.all: \
  .\AMouse.res \
  .\AMouse.dll

.rc.res:
      @echo " Compile::Resource Compiler "
      rc.exe -r -i . -i .. -i ..\.. $(RDB) %s %|fF.RES

{..}.rc.res:
      @echo " Compile::Resource Compiler "
      rc.exe -r -i . -i .. -i ..\.. $(RDB) %s %|fF.RES

.idl.ih:
      @echo " Compile::SOM Compiler "
      sc.exe -p -maddstar -mnoint -I. %s
      @sed -e "s/#pragma checkout(suspend)/#pragma info(none)/"   $@ > $*.tmp
      @sed -e "s/#pragma checkout(resume)/#pragma info(restore)/" $*.tmp > $@
      @del $*.tmp

.c.obj:
      @echo " Compile::C++ Compiler "
      icc.exe /I. /I.. /I..\.. /Ss $(CDB) $(CTR) /Q /Wcnveffparprorearetuse /Gm /Ge- /G5 /Gf /Fo"%|fF.obj" /Ms /C %s

{..}.c.obj:
      @echo " Compile::C++ Compiler "
      icc.exe /I. /I.. /I..\.. /Ss $(CDB) $(CTR) /Q /Wcnveffparprorearetuse /Gm /Ge- /G5 /Gf /Fo"%|fF.obj" /Ms /C %s

.\amouse.dll: \
    .\amouse.obj \
    .\amousedata.obj \
    .\dialogs.obj \
    .\common.obj \
    .\commonDlg.obj \
    .\Vendor.obj \
    $(OTR) \
    $(DTR) \
    .\amouse.res \
    {$(LIB)}amouse.def
      @echo "Link::Linker "
      icc.exe @<<
 /B" /dbgpack /pmtype:pm /nologo /m /noi /exep /packc /packd /al:16"
 /Feamouse.dll
 somtk.lib
 cutil.lib
 amouse.def
 .\amouse.obj
 .\amousedata.obj
 .\dialogs.obj
 .\common.obj
 .\commonDlg.obj
 .\Vendor.obj
 $(OTR)
 $(DTR)
<<
      @echo "Bind::Resource Bind "
      rc.exe -p -x .\amouse.res amouse.dll

!include MAKEFILE.Dep

cleanall:
      @if exist *.obj del *.obj
      @if exist *.res del *.res
      @if exist *.dll del *.dll

copyall:
      @if exist AMouse.dll copy AMouse.dll ..\Install_Source

