  AMouse - Der Treiber fr M„use mit Tastenrad

Dieser Treiber arbeitet mit allen g„ngigen Standardm„usen,
sowie M„usen mit Tastenrad, wie z. B.:
- Logitech Pilot Mouse+ mit serieller oder PS/2-Mausschnittstelle
- Logitech Mouse Man+
- Microsoft Intellimouse
- IBM Scrollpoint Mouse
- Typhoon 40159
- Trust 250S
- USB-M„usen

Die Eigenschaften der Maus k”nnen ber das Mauskonfigurations-
programm im Systemkonfigurationsordner eingestellt werden.

Alternativ wird ein Konfigurationsprogramm mitgeliefert, das
ohne die Workplace Shell arbeiten kann.
