LIBRARY XWPMOUSE INITGLOBAL TERMGLOBAL

DESCRIPTION '@#NB:X.XX.XX#@ AMouse XWorkplace Widget (c) nb-software 2001...2004'

DATA MULTIPLE NONSHARED READWRITE LOADONCALL

CODE LOADONCALL

PROTMODE

EXPORTS
   WgtInitModule      @1
   WgtUnInitModule    @2
   WgtQueryVersion    @3

